[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
#config.workspace = true
sqlx.workspace = true
anyhow.workspace = true
axum.workspace = true
#router.workspace = true
postgres.workspace = true
dotenvy.workspace = true
serde.workspace = true